kind: pipeline
type: docker
name: ci-cd-pipeline

steps:
  - name: lint
    image: golangci/golangci-lint:latest
    commands:
      - golangci-lint run

  - name: test
    image: golang:1.26
    commands:
      - go test -v ./...

  - name: docker-build-and-push
    image: plugins/docker
    settings:
      repo: kad0602/go-gin-api
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags:
        - latest
        - ${DRONE_COMMIT_SHA:0:7}
    when:
      branch:
        - main
      event:
        - push

  # Деплой у Google Cloud Run
  - name: deploy-to-cloud-run
    image: google/cloud-sdk:alpine
    environment:
      # Беремо користувацький JSON із секретів Drone CI
      GCP_CREDENTIALS:
        from_secret: gcp_credentials
    commands:
      # 1. Зберігаємо JSON у тимчасовий файл всередині контейнера Дрона
      - echo $GCP_CREDENTIALS > /tmp/gcp-key.json
      
      # 2. Авторизація за допомогою файлу облікових даних користувача
      - gcloud auth login --cred-file=/tmp/gcp-key.json
      
      # 3. Вказуємо ID проєкту
      - gcloud config set project exalted-density-496814-q5
      
      # 4. Команда розгортання в Cloud Run
      - gcloud run deploy go-gin-api \
          --image docker.io/kad0602/go-gin-api:${DRONE_COMMIT_SHA:0:7} \
          --region europe-central2 \
          --platform managed \
          --allow-unauthenticated \
          --update-secrets=MY_API_KEY=my_api_key:latest
    when:
      branch:
        - main
      event:
        - push